name: Build Python Executable

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: List files before build
      run: |
        ls -la
        ls -la src/

    - name: Set directory permissions
      run: chmod -R 777 src/

    - name: Build executable
      run: |
        pyinstaller --onefile --distpath src src/main.py

    - name: List files after build
      run: |
        ls -la
        ls -la src/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-executable
        path: src/
